import { create } from "zustand";


const useEnrolledStore = create((set) => ({
    enrolledList: [
        {
            id: 1,
            first_name: "John",
            last_name: "Doe",
            middle_name: "Aaron",
            program: "Licensure Examination for Teachers",
            email: "johndoe@email.com",
            status: "Enrolled",
            phone: "09123456789",
            birthday: "1995-01-01",
            gender: "Male",
            house_no_st: "123 Main St",
            province: "Metro Manila",
            city: "Quezon City",
            barangay: "Barangay Central",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "95/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "90/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "85/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "92/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "88/100"},
            ]
        },
        {
            id: 2,
            first_name: "Bea",
            last_name: "Soriano",
            middle_name: "Marie",
            program: "Certificate in Teaching Program",
            email: "beasoriano@email.com",
            status: "Enrolled",
            phone: "09129876543",
            birthday: "1994-02-15",
            gender: "Female",
            house_no_st: "456 Elm St",
            province: "Metro Manila",
            city: "Manila",
            barangay: "Barangay 123",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "90/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "85/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "80/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "95/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "88/100"},
            ]
        },
        {
            id: 3,
            first_name: "Mark",
            last_name: "Smith",
            middle_name: "Anthony",
            program: "Licensure Examination for Teachers",
            email: "marksmith@email.com",
            status: "Enrolled",
            phone: "09127654321",
            birthday: "1993-03-10",
            gender: "Male",
            house_no_st: "789 Oak St",
            province: "Metro Manila",
            city: "Pasig",
            barangay: "Barangay San Antonio",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "85/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "90/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "88/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "92/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "95/100"},
            ]
        },
        {
            id: 4,
            first_name: "Jane",
            last_name: "Doe",
            middle_name: "Marie",
            program: "Certificate in Teaching Program",
            email: "janedoe@email.com",
            status: "Enrolled",
            phone: "09121234567",
            birthday: "1996-04-20",
            gender: "Female",
            house_no_st: "101 Pine St",
            province: "Metro Manila",
            city: "Taguig",
            barangay: "Barangay Fort Bonifacio",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 3.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "80/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "85/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "82/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "88/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "90/100"},
            ]
        },
        {
            id: 5,
            first_name: "John",
            last_name: "Smith",
            middle_name: "Michael",
            program: "Licensure Examination for Teachers",
            email: "johnsmith@email.com",
            status: "Drop",
            phone: "09122334455",
            birthday: "1992-05-05",
            gender: "Male",
            house_no_st: "102 Maple St",
            province: "Metro Manila",
            city: "Makati",
            barangay: "Barangay Poblacion",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "75/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "80/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "78/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "82/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "85/100"},
            ]
        },
        {
            id: 6,
            first_name: "Alice",
            last_name: "Johnson",
            middle_name: "Elizabeth",
            program: "Certificate in Teaching Program",
            email: "alicejohnson@email.com",
            status: "Withdrawn",
            phone: "09129998877",
            birthday: "1991-06-12",
            gender: "Female",
            house_no_st: "103 Cedar St",
            province: "Metro Manila",
            city: "Caloocan",
            barangay: "Barangay 178",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "80/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "85/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "82/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "88/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "90/100"},
            ]
        },
        {
            id: 7,
            first_name: "Bob",
            last_name: "Brown",
            middle_name: "Lee",
            program: "Certificate in Teaching Program",
            email: "bobbrown@email.com",
            status: "Enrolled",
            phone: "09125556677",
            birthday: "1990-07-25",
            gender: "Male",
            house_no_st: "104 Birch St",
            province: "Metro Manila",
            city: "Valenzuela",
            barangay: "Barangay Malinta",
            courses: [
                { name: "Purposive Communication", grade: 2.5 },
                { name: "Mathematics", grade: 2.0 },
                { name: "The Teaching Profession", grade: 3.0 },
                { name: "Art Appreciation", grade: 2.25 },
            ],
            assessment: [
                {name: "Quiz 1", coursename: "Mathematics", score: "85/100"},
                {name: "Quiz 2", coursename: "Mathematics", score: "90/100"},
                {name: "Activity 1", coursename: "Mathematics", score: "88/100"},
                {name: "Activity 2", coursename: "Mathematics", score: "92/100"},
                {name: "Quiz 3", coursename: "Mathematics", score: "95/100"},
            ]
        }
    ],
    newEnrolled: [],
}));

export default useEnrolledStore;
